[package]
name = "bevy_ardh_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_ardh = { version = "0.1.0", path = "../bevy_ardh" }
bevy = "0.12.1"
